# import libraries
library(tidyverse)
library(dplyr)

# import raw data
raw_data <- readr::read_csv("./1249534s1-s6_dataS1.csv",skip=3)

# Clean data: fill the experiment column with experiment names
cleaned_data <- raw_data %>%
  fill(Experiment, .direction = "down")

# Add a column with the log response ratio (LRR)
cleaned_data <- cleaned_data %>%
  mutate(LRR = log(`increased CO2...9` / `ambient CO2...8`))

cleaned_data['LRR']

# Compute the means of LRR for each phase
agg_data_by_phase <- cleaned_data %>%
  mutate(phase = case_when(
    `Time (years)` < 3 ~ "Early",
    `Time (years)` >= 3 & `Time (years)` <= 6 ~ "Mid",
    `Time (years)` > 6 ~ "Late"
  )) %>%
  group_by(phase) %>%
  summarise(mean_LRR = mean(LRR, na.rm = TRUE)) %>%
  drop_na() %>%  # Remove NaN rows
  mutate(phase = factor(phase, levels = c("Early", "Mid", "Late"))) %>%
  arrange(phase)  # Ensure correct sorting

# Show results as a table
knitr::kable(agg_data_by_phase)

# Answers to the exercises:

# - What are the data that you are looking at?
#     We are looking at SOM data for different experiments, with both ambient and enhanced CO2 conditions. SOC is measured at different time points. Some experiments have additional variables, like N-limitation.

# - What do you expect your analysis to show, what is your hypothesis? How should soil organic matter content change under elevated CO2?
#     The idea of CO2 fertilization could hypothesize that elevated CO2 increases SOC content due to enhanced plant productivity and root biomass, leading to higher soil carbon inputs. Alternatively, decomposition rates might counteract this, resulting in no significant or even negative changes.

# - Interpret your results after aggregating the data: What do your final numbers mean? Do they support your initial hypothesis? Why so, why not?
#     The early phase shows almost no effect. This is quite expected, as it takes time for a soil to adjust to new conditions. Therefore the mid-phase proved the hypothesis: There is a positive mean LRR, meaning that the enhanced CO2 setup has a higher SOC content than the ambient conditions. The late phase however, corresponding to a negative LRR, contradicts my hypothesis. This could be due to increased microbial decomposition rates, that offset carbon inputs or experimental condition variations across studies. Also, SOC accumulation is a slow process that might not be captured fully within these experiments. 
